=== seui-engine/raytracing-csg-renderer/lib/schema-generator/schema.json
{
  "$schema": "http://json-schema.org/draft-07/schema#",
  "title": "DeserializableScene",
  "type": "object",
  "required": [
    "ambientLight",
    "camera",
    "lights",
    "objects",
    "skyColor"
  ],
  "properties": {
    "ambientLight": {
      "$ref": "#/definitions/HDRColor"
    },
    "camera": {
      "$ref": "#/definitions/DeserializableCamera"
    },
    "lights": {
      "type": "array",
      "items": {
        "$ref": "#/definitions/DeserializableLight"
      }
    },
    "objects": {
      "type": "array",
      "items": {
        "$ref": "#/definitions/DeserializableRTObject"
      }
    },
    "skyColor": {
      "$ref": "#/definitions/HDRColor"
    }
  },
  "additionalProperties": false,
  "definitions": {
    "DeserializableCamera": {
      "oneOf": [
        {
          "type": "object",
          "required": [
            "fov",
            "fovMode",
            "type"
          ],
          "properties": {
            "direction": {
              "$ref": "#/definitions/Direction"
            },
            "fov": {
              "type": "number",
              "format": "float"
            },
            "fovMode": {
              "$ref": "#/definitions/FovMode"
            },
            "position": {
              "$ref": "#/definitions/Position"
            },
            "type": {
              "type": "string",
              "enum": [
                "perspective"
              ]
            }
          },
          "additionalProperties": false
        }
      ]
    },
    "DeserializableLight": {
      "oneOf": [
        {
          "type": "object",
          "required": [
            "type"
          ],
          "properties": {
            "color": {
              "$ref": "#/definitions/HDRColor"
            },
            "position": {
              "$ref": "#/definitions/Position"
            },
            "type": {
              "type": "string",
              "enum": [
                "point"
              ]
            }
          },
          "additionalProperties": false
        },
        {
          "type": "object",
          "required": [
            "type"
          ],
          "properties": {
            "color": {
              "$ref": "#/definitions/HDRColor"
            },
            "direction": {
              "$ref": "#/definitions/Direction"
            },
            "type": {
              "type": "string",
              "enum": [
                "directional"
              ]
            }
          }
        }
      ]
    },
    "DeserializableRTObject": {
      "oneOf": [
        {
          "type": "object",
          "required": [
            "a",
            "b",
            "type"
          ],
          "properties": {
            "a": {
              "$ref": "#/definitions/DeserializableRTObject"
            },
            "b": {
              "$ref": "#/definitions/DeserializableRTObject"
            },
            "type": {
              "type": "string",
              "enum": [
                "union"
              ]
            }
          },
          "additionalProperties": false
        },
        {
          "type": "object",
          "required": [
            "a",
            "b",
            "type"
          ],
          "properties": {
            "a": {
              "$ref": "#/definitions/DeserializableRTObject"
            },
            "b": {
              "$ref": "#/definitions/DeserializableRTObject"
            },
            "type": {
              "type": "string",
              "enum": [
                "intersection"
              ]
            }
          },
          "additionalProperties": false
        },
        {
          "type": "object",
          "required": [
            "a",
            "b",
            "type"
          ],
          "properties": {
            "a": {
              "$ref": "#/definitions/DeserializableRTObject"
            },
            "b": {
              "$ref": "#/definitions/DeserializableRTObject"
            },
            "type": {
              "type": "string",
              "enum": [
                "difference"
              ]
            }
          },
          "additionalProperties": false
        },
        {
          "type": "object",
          "required": [
            "type"
          ],
          "properties": {
            "albedo": {
              "$ref": "#/definitions/LDRColor"
            },
            "position": {
              "$ref": "#/definitions/Position"
            },
            "radius": {
              "default": 1.0,
              "type": "number",
              "format": "float"
            },
            "type": {
              "type": "string",
              "enum": [
                "sphere"
              ]
            }
          },
          "additionalProperties": false
        },
        {
          "type": "object",
          "required": [
            "type"
          ],
          "properties": {
            "albedo": {
              "$ref": "#/definitions/LDRColor"
            },
            "normal": {
              "$ref": "#/definitions/Direction"
            },
            "position": {
              "$ref": "#/definitions/Position"
            },
            "type": {
              "type": "string",
              "enum": [
                "plane"
              ]
            }
          },
          "additionalProperties": false
        },
        {
          "type": "object",
          "required": [
            "type"
          ],
          "properties": {
            "albedo": {
              "$ref": "#/definitions/LDRColor"
            },
            "position": {
              "$ref": "#/definitions/Position"
            },
            "scale": {
              "$ref": "#/definitions/Scale"
            },
            "type": {
              "type": "string",
              "enum": [
                "cube"
              ]
            }
          },
          "additionalProperties": false
        },
        {
          "type": "object",
          "required": [
            "type"
          ],
          "properties": {
            "albedo": {
              "$ref": "#/definitions/LDRColor"
            },
            "c000": {
              "default": 0.0,
              "type": "number",
              "format": "float"
            },
            "c001": {
              "default": 0.0,
              "type": "number",
              "format": "float"
            },
            "c002": {
              "default": 0.0,
              "type": "number",
              "format": "float"
            },
            "c010": {
              "default": 0.0,
              "type": "number",
              "format": "float"
            },
            "c011": {
              "default": 0.0,
              "type": "number",
              "format": "float"
            },
            "c020": {
              "default": 0.0,
              "type": "number",
              "format": "float"
            },
            "c100": {
              "default": 0.0,
              "type": "number",
              "format": "float"
            },
            "c101": {
              "default": 0.0,
              "type": "number",
              "format": "float"
            },
            "c110": {
              "default": 0.0,
              "type": "number",
              "format": "float"
            },
            "c200": {
              "default": 0.0,
              "type": "number",
              "format": "float"
            },
            "inside": {
              "$ref": "#/definitions/Position"
            },
            "position": {
              "$ref": "#/definitions/Position"
            },
            "type": {
              "type": "string",
              "enum": [
                "quadric"
              ]
            }
          },
          "additionalProperties": false
        },
        {
          "type": "object",
          "required": [
            "inside",
            "type"
          ],
          "properties": {
            "albedo": {
              "$ref": "#/definitions/LDRColor"
            },
            "c000": {
              "default": 0.0,
              "type": "number",
              "format": "float"
            },
            "c001": {
              "default": 0.0,
              "type": "number",
              "format": "float"
            },
            "c002": {
              "default": 0.0,
              "type": "number",
              "format": "float"
            },
            "c003": {
              "default": 0.0,
              "type": "number",
              "format": "float"
            },
            "c010": {
              "default": 0.0,
              "type": "number",
              "format": "float"
            },
            "c011": {
              "default": 0.0,
              "type": "number",
              "format": "float"
            },
            "c012": {
              "default": 0.0,
              "type": "number",
              "format": "float"
            },
            "c020": {
              "default": 0.0,
              "type": "number",
              "format": "float"
            },
            "c021": {
              "default": 0.0,
              "type": "number",
              "format": "float"
            },
            "c030": {
              "default": 0.0,
              "type": "number",
              "format": "float"
            },
            "c100": {
              "default": 0.0,
              "type": "number",
              "format": "float"
            },
            "c101": {
              "default": 0.0,
              "type": "number",
              "format": "float"
            },
            "c102": {
              "default": 0.0,
              "type": "number",
              "format": "float"
            },
            "c110": {
              "default": 0.0,
              "type": "number",
              "format": "float"
            },
            "c111": {
              "default": 0.0,
              "type": "number",
              "format": "float"
            },
            "c120": {
              "default": 0.0,
              "type": "number",
              "format": "float"
            },
            "c200": {
              "default": 0.0,
              "type": "number",
              "format": "float"
            },
            "c201": {
              "default": 0.0,
              "type": "number",
              "format": "float"
            },
            "c210": {
              "default": 0.0,
              "type": "number",
              "format": "float"
            },
            "c300": {
              "default": 0.0,
              "type": "number",
              "format": "float"
            },
            "inside": {
              "$ref": "#/definitions/Position"
            },
            "position": {
              "$ref": "#/definitions/Position"
            },
            "type": {
              "type": "string",
              "enum": [
                "quadratic"
              ]
            }
          }
        }
      ]
    },
    "Direction": {
      "title": "Direction",
      "description": "A 3D normal, either as an object `{x, y, z}` or a tuple `[x, y, z]`.",
      "oneOf": [
        {
          "type": "object",
          "required": [
            "x",
            "y",
            "z"
          ],
          "properties": {
            "x": {
              "type": "number",
              "format": "float"
            },
            "y": {
              "type": "number",
              "format": "float"
            },
            "z": {
              "type": "number",
              "format": "float"
            }
          },
          "additionalProperties": false
        },
        {
          "type": "array",
          "items": {
            "type": "number",
            "format": "float"
          },
          "maxItems": 3,
          "minItems": 3
        }
      ]
    },
    "FovMode": {
      "oneOf": [
        {
          "type": "object",
          "required": [
            "type"
          ],
          "properties": {
            "type": {
              "type": "string",
              "enum": [
                "x"
              ]
            }
          },
          "additionalProperties": false
        },
        {
          "type": "object",
          "required": [
            "type"
          ],
          "properties": {
            "type": {
              "type": "string",
              "enum": [
                "y"
              ]
            }
          },
          "additionalProperties": false
        },
        {
          "type": "object",
          "required": [
            "aspectRatio",
            "type"
          ],
          "properties": {
            "aspectRatio": {
              "type": "number",
              "format": "float"
            },
            "type": {
              "type": "string",
              "enum": [
                "cover"
              ]
            }
          },
          "additionalProperties": false
        },
        {
          "type": "object",
          "required": [
            "aspectRatio",
            "type"
          ],
          "properties": {
            "aspectRatio": {
              "type": "number",
              "format": "float"
            },
            "type": {
              "type": "string",
              "enum": [
                "contain"
              ]
            }
          },
          "additionalProperties": false
        }
      ]
    },
    "HDRColor": {
      "title": "HDRColor",
      "description": "A HDR color, either as an object `{r, g, b}` or a tuple `[r, g, b]`.",
      "oneOf": [
        {
          "type": "object",
          "required": [
            "b",
            "g",
            "r"
          ],
          "properties": {
            "b": {
              "type": "number",
              "format": "float",
              "minimum": 0.0
            },
            "g": {
              "type": "number",
              "format": "float",
              "minimum": 0.0
            },
            "r": {
              "type": "number",
              "format": "float",
              "minimum": 0.0
            }
          },
          "additionalProperties": false
        },
        {
          "type": "array",
          "items": {
            "type": "number",
            "format": "float",
            "minimum": 0.0
          },
          "maxItems": 3,
          "minItems": 3
        }
      ]
    },
    "LDRColor": {
      "title": "LDRColor",
      "description": "A LDR color, either as an object `{r, g, b}` or a tuple `[r, g, b]`.",
      "oneOf": [
        {
          "type": "object",
          "required": [
            "b",
            "g",
            "r"
          ],
          "properties": {
            "b": {
              "type": "number",
              "format": "float",
              "maximum": 1.0,
              "minimum": 0.0
            },
            "g": {
              "type": "number",
              "format": "float",
              "maximum": 1.0,
              "minimum": 0.0
            },
            "r": {
              "type": "number",
              "format": "float",
              "maximum": 1.0,
              "minimum": 0.0
            }
          },
          "additionalProperties": false
        },
        {
          "type": "array",
          "items": {
            "type": "number",
            "format": "float",
            "maximum": 1.0,
            "minimum": 0.0
          },
          "maxItems": 3,
          "minItems": 3
        }
      ]
    },
    "Position": {
      "title": "Position",
      "description": "A 3D position, either as an object `{x, y, z}` or a tuple `[x, y, z]`.",
      "oneOf": [
        {
          "type": "object",
          "required": [
            "x",
            "y",
            "z"
          ],
          "properties": {
            "x": {
              "type": "number",
              "format": "float"
            },
            "y": {
              "type": "number",
              "format": "float"
            },
            "z": {
              "type": "number",
              "format": "float"
            }
          },
          "additionalProperties": false
        },
        {
          "type": "array",
          "items": {
            "type": "number",
            "format": "float"
          },
          "maxItems": 3,
          "minItems": 3
        }
      ]
    },
    "Scale": {
      "title": "Scale",
      "description": "A 3D scale, either as an object `{x, y, z}` or a tuple `[x, y, z]`.",
      "oneOf": [
        {
          "type": "object",
          "required": [
            "x",
            "y",
            "z"
          ],
          "properties": {
            "x": {
              "type": "number",
              "format": "float",
              "minimum": 0.0
            },
            "y": {
              "type": "number",
              "format": "float",
              "minimum": 0.0
            },
            "z": {
              "type": "number",
              "format": "float",
              "minimum": 0.0
            }
          },
          "additionalProperties": false
        },
        {
          "type": "array",
          "items": {
            "type": "number",
            "format": "float",
            "minimum": 0.0
          },
          "maxItems": 3,
          "minItems": 3
        }
      ]
    }
  }
}

=== seui-engine/raytracing-csg-renderer/assets/quadratic-test.json
{
  "camera": {
    "type": "perspective",
    "fov": 90,
    "fovMode": {
      "type": "cover",
      "aspectRatio": 1.7777777777
    },
    "position": [0, -40, 10],
    "direction": [0, 1, 0]
  },
  "objects": [
    {
      "type": "quadratic",
      "albedo": [0, 1, 0],
      "position": [0, 0, 0],
      "inside": [0, 0, 100],
      "c300": 1,
      "c030": 1,
      "c003": 1,
      "c000": -8,
      "c001": 0,
      "c002": 0,
      "c010": 0,
      "c011": 0,
      "c012": 0,
      "c020": 0,
      "c021": 0,
      "c100": 0,
      "c101": 0,
      "c102": 0,
      "c110": 0,
      "c111": 0,
      "c120": 0,
      "c200": 0,
      "c201": 0,
      "c210": 0
    },
    {
      "type": "sphere",
      "position": [0, 0, 0],
      "albedo": [1, 0, 0],
      "radius": 1
    }
  ],
  "lights": [
    {
      "type": "point",
      "position": [0, 0, 10],
      "color": [200, 200, 200]
    }
  ],
  "skyColor": [0.1, 0.11, 0.2],
  "ambientLight": [0.1, 0.1, 0.1]
}

=== seui-engine/raytracing-csg-renderer/assets/test.json
{
  "camera": {
    "type": "perspective",
    "fov": 90,
    "fovMode": {
      "type": "cover",
      "aspectRatio": 1.7777777777
    },
    "position": [0, -10, 0],
    "direction": [0, 1, 0]
  },
  "objects": [
    {
      "type": "difference",
      "a": {
        "type": "intersection",
        "a": {
          "type": "sphere",
          "position": [-2, 0, -3],
          "radius": 1.33,
          "albedo": [0.2, 0.2, 1]
        },
        "b": {
          "type": "cube",
          "position": [-2, 0, -3],
          "scale": [1, 1, 1],
          "albedo": [1, 0.2, 0.2]
        }
      },
      "b": {
        "type": "sphere",
        "position": [-2, 0, -3],
        "radius": 1.2,
        "albedo": [0.2, 1, 0.2]
      }
    },
    {
      "type": "difference",
      "a": {
        "type": "intersection",
        "a": {
          "type": "sphere",
          "position": [2, 0, -3],
          "radius": 1.33,
          "albedo": [0.2, 0.2, 1]
        },
        "b": {
          "type": "cube",
          "position": [2, 0, -3],
          "scale": [1, 1, 1],
          "albedo": [1, 0.2, 0.2]
        }
      },
      "b": {
        "type": "sphere",
        "position": [2, 0, -3],
        "radius": 1.2,
        "albedo": [0.2, 1, 0.2]
      }
    },
    {
      "type": "plane",
      "position": [0, 0, -5],
      "normal": [0, 0, 1],
      "albedo": [1, 1, 1]
    },
    {
      "type": "sphere",
      "position": [-3, 0, 0],
      "radius": 1,
      "albedo": [1, 0.5, 0.5]
    },
    {
      "type": "sphere",
      "position": [0, 0, 0],
      "radius": 1,
      "albedo": [0.5, 1, 0.5]
    },
    {
      "type": "cube",
      "position": [3, 0, 0],
      "scale": [1, 1, 1],
      "albedo": [0.5, 0.5, 1]
    }
  ],
  "lights": [
    {
      "type": "point",
      "position": [0, 0, 14],
      "color": [20, 20, 20]
    }
  ],
  "skyColor": [0.1, 0.11, 0.2],
  "ambientLight": [0.1, 0.1, 0.1]
}
